import createFetchClient from 'openapi-fetch';
import createClient from 'openapi-react-query';

import type { paths } from './schemas/schema'; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: 'http://localhost:3001/',
});

export const $riskApi = createClient(fetchClient);
