version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=user12345
      - MSSQL_PID=Developer
    ports:
      - '1433:1433'
    volumes:
      - db_data:/var/opt/mssql
      - ./scripts/create-database.sql:/docker-entrypoint-initdb.d/create-database.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
