version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: denali
      POSTGRES_DB: denali
    ports:
      - '5432:5432'
    networks:
      - denali-network
  db-2:
    image: postgres:13
    container_name: crescent-view-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: crescent
      POSTGRES_DB: crescent-view
    ports:
      - '5433:5432'
    networks:
      - denali-network
networks:
  denali-network:
    driver: bridge
