/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk-rule/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve a single RiskRule */
        get: operations["getOneBaseRiskRulesControllerRiskRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/risk-rule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve multiple RiskRules */
        get: operations["getManyBaseRiskRulesControllerRiskRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GetManyRiskRuleResponseDto: {
            data: components["schemas"]["RiskRule"][];
            count: number;
            total: number;
            page: number;
            pageCount: number;
        };
        RiskRuleParam: {
            /** @description Primary key identifier of the rule parameter. */
            id: number;
            /** @description Foreign key referencing the parent risk rule. */
            ruleId?: number;
            /** @description The related risk rule. */
            rule: components["schemas"]["RiskRule"];
            /** @description Short name or code for the parameter. */
            shortName?: string;
            /** @description Detailed definition or explanation of the parameter. */
            definition?: string;
            /** @description List of parameter values associated with this rule parameter. */
            values: components["schemas"]["RiskRuleParamValue"][];
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
        };
        RiskRuleParamValue: {
            /** @description Primary key identifier of the parameter value. */
            id: number;
            /** @description Foreign key referencing the related rule parameter. */
            ruleParamId?: number;
            /** @description Numeric value assigned to this parameter. */
            value?: number;
            /**
             * Format: date-time
             * @description Date from which this parameter value is effective.
             */
            effectiveDate: string;
            /** @description The related risk rule. */
            rule: components["schemas"]["RiskRule"];
            /** @description The related rule parameter. */
            parameter: components["schemas"]["RiskRuleParam"];
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
        };
        RiskSource: {
            /** @description Primary key identifier of the source. */
            id: number;
            /** @description Definition or name of the source. */
            definition?: string;
            /** @description Collection of risk rules associated with this source. */
            rules: components["schemas"]["RiskRule"][];
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
        };
        RiskRuleType: {
            /** @description Primary key identifier of the rule type. */
            id: number;
            /** @description Short code for the rule type. */
            code?: string;
            /** @description Definition or meaning of the rule type. */
            definition?: string;
            /** @description Collection of risk rules under this type. */
            rules: components["schemas"]["RiskRule"][];
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
        };
        RiskRule: {
            /** @description Primary key identifier of the risk rule. */
            id: number;
            /** @description Foreign key referencing the risk source. */
            sourceId?: number;
            /** @description Foreign key referencing the rule type. */
            ruleTypeId?: number;
            /** @description Detailed definition or explanation of the rule. */
            definition?: string;
            /** @description Collection of parameter values linked to this rule. */
            paramValues: components["schemas"]["RiskRuleParamValue"][];
            /** @description Collection of parameters linked to this rule. */
            parameters: components["schemas"]["RiskRuleParam"][];
            /** @description Associated risk source entity. */
            source: components["schemas"]["RiskSource"];
            /** @description Associated rule type entity. */
            ruleType: components["schemas"]["RiskRuleType"];
            /**
             * Format: date-time
             * @description Record creation timestamp.
             */
            createdAt: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getOneBaseRiskRulesControllerRiskRule: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Get one base response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskRule"];
                };
            };
        };
    };
    getManyBaseRiskRulesControllerRiskRule: {
        parameters: {
            query?: {
                /** @description Selects resource fields. <a href="https://github.com/nestjsx/crud/wiki/Requests#select" target="_blank">Docs</a> */
                fields?: string[];
                /** @description Adds search condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#search" target="_blank">Docs</a> */
                s?: string;
                /** @description Adds filter condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#filter" target="_blank">Docs</a> */
                filter?: string[];
                /** @description Adds OR condition. <a href="https://github.com/nestjsx/crud/wiki/Requests#or" target="_blank">Docs</a> */
                or?: string[];
                /** @description Adds sort by field. <a href="https://github.com/nestjsx/crud/wiki/Requests#sort" target="_blank">Docs</a> */
                sort?: string[];
                /** @description Adds relational resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#join" target="_blank">Docs</a> */
                join?: string[];
                /** @description Limit amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#limit" target="_blank">Docs</a> */
                limit?: number;
                /** @description Offset amount of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#offset" target="_blank">Docs</a> */
                offset?: number;
                /** @description Page portion of resources. <a href="https://github.com/nestjsx/crud/wiki/Requests#page" target="_blank">Docs</a> */
                page?: number;
                /** @description Reset cache (if was enabled). <a href="https://github.com/nestjsx/crud/wiki/Requests#cache" target="_blank">Docs</a> */
                cache?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetManyRiskRuleResponseDto"];
                };
            };
        };
    };
}
