import type { Metadata } from 'next';

import { ThemeProvider } from '@/ui/theme';
import { ReactQueryProvider } from '@/libs/shared/providers/query-client';
import { FronteggAppProvider } from '@frontegg/nextjs/app';
import { JSX } from 'react';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  const authOptions = {
    keepSessionAlive: true, // Uncomment this in order to maintain the session alive
  };
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <FronteggAppProvider authOptions={authOptions}>
          <ThemeProvider>
            <ReactQueryProvider>{children}</ReactQueryProvider>
          </ThemeProvider>
        </FronteggAppProvider>
      </body>
    </html>
  );
}
