export type RiskRadarExceptionsListRow = {
  pkRiskRadarExceptions: number;
  dNetDepAmt?: number;
  sDBA?: string;
  sSolutionConsultant?: string;
  bSelfGen?: string;
  iTransAmtAboveLimit?: number;
  iNumOfKeyedTransAboveLimit?: number;
  iBatchVolAboveLimit?: number;
  iDupCard?: number;
  bNewAcct?: string;
  iDupBin?: number;
  iLatePostTrans?: number;
  iFgnkeyedTrans?: number;
  iNoAuthTrans?: number;
  iChbkOrIRR?: number;
  bNextDayFundingAcct?: string;
  sMID: string;
  sNTUserID?: string;
  dtTransmission?: Date;
  bDivert?: string;
  sAMEXOptBlueInd?: string;
  iAuthCaptureAmtLargeVariation?: number;
  bRiskWatch?: string;
  dSettlementBalance?: number;
  iAvgBatch?: number;
  iNegDailyBatches?: number;
  iMototIoAVS?: number;
  iAuthDecline?: number;
  iTotalPoints?: number;
  dAuthDeclineAmt: number;
  sUserReviewed?: string;
  dtActivated?: Date;
  dtCreated: Date;
  sChannel: string;
  iAutoHold?: number;
  dtAutoApproved?: Date;
  iTransAmtAboveHighTicketLimit?: number;
  iCreditRule?: number;
  iSalesChannelRule?: number;
  iFundingExclusionAndException?: number;
  dAuthNonDeclinedAmt: number;
  sReseller: string;
  sReferralPartner: string;
  sISV: string;
  // Fallback when data comes from leads table
  leadName?: string;

  // Added for table ID
  id?: number;
};
