[SERVICE]
    log_level debug
    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf
    # Primarily for basic status checks and internal diagnostics.
    # More focused on high-level service health and debugging.
    HTTP_Server    On
    HTTP_Port      2020
    # This port is for continuous scraping of metrics, providing much more
    # granular, detailed operational data that can be visualized and alerted on.
    Metrics        On
    Metrics_Port   9101
    # Increase the retry limit
    Retry_Limit    5

[INPUT]
    Name forward
    Tag  forward.data
    Listen 0.0.0.0
    port 24224
    Buffer_Chunk_Size 1M
    Buffer_Max_Size 6M

[FILTER]
    Name parser
    Match forward.*
    Key_Name log
    Parser docker
    Reserve_Data On

[FILTER]
    Name parser
    Match forward.*
    Key_Name log
    Parser denali_structured_logs
    Reserve_Data On

[FILTER]
    Name modify
    Match forward.*
    # Extract the fields we want to keep at the top level
    Copy level level
    Copy msg msg
    Copy res.statusCode statusCode

[OUTPUT]
    Name es
    Match *
    Host ${OPEN_SEARCH_NODE_URL}
    Port 443
    Index ${OPEN_SEARCH_LOGSTASH_PREFIX}
    # When Logstash_Format is enabled, the Index name is composed using a prefix and the date
    Logstash_Format True
    Logstash_Prefix ${OPEN_SEARCH_LOGSTASH_PREFIX}
    Logstash_DateFormat %Y.%m.%d
    HTTP_User ${OPEN_SEARCH_USERNAME}
    HTTP_Passwd ${OPEN_SEARCH_PASSWORD}
    Suppress_Type_Name On
    Include_Tag_Key On
    Tag_Key _flb-key
    # Retry configuration
    Retry_Limit 5
    # TLS configuration
    tls On
    tls.verify On
    # Trace errors
    Trace_Error On
    Trace_Output On
