[SERVICE]
    log_level debug
    # Parsers File
    # ============
    # specify an optional 'Parsers' configuration file
    parsers_file parsers.conf
    # Primarily for basic status checks and internal diagnostics.
    # More focused on high-level service health and debugging.
    HTTP_Server    On
    HTTP_Port      2020
    # This port is for continuous scraping of metrics, providing much more
    # granular, detailed operational data that can be visualized and alerted on.
    Metrics        On
    Metrics_Port   9101

[INPUT]
    Name forward
    Tag  forward.data
    Listen 0.0.0.0
    port 24224

[FILTER]
    Name parser
    Match forward.*
    Key_Name log
    Parser docker

[OUTPUT]
    Name es
    Match *
    Host ${OPEN_SEARCH_NODE_URL}
    Port 443
    # When Logstash_Format is enabled, the Index name is composed using a prefix and the date
    Logstash_Format True
    Logstash_Prefix ${OPEN_SEARCH_LOGSTASH_PREFIX}
    HTTP_User ${OPEN_SEARCH_USERNAME}
    HTTP_Passwd ${OPEN_SEARCH_PASSWORD}
    Suppress_Type_Name On
    # Alternative time key, useful if your log entries contain an @timestamp field that is used by Elasticsearch
    # Time_Key es_time
    # If your Elasticsearch is using TLS, configure this
    #AWS_Auth On
    #AWS_Region us-west-2
    tls On
    tls.verify On
