name: DENALI CD (Deploy Staging)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  code-checks:
    name: Run code quality tools
    uses: ./.github/workflows/_code_checks.yaml

  versioning:
    name: Generate build number
    uses: ./.github/workflows/_versioning.yaml
    with:
      release-type: 'pre-release'

  deploy-web:
    name: Deploy DENALI Web to AWS
    needs: [versioning]
    uses: ./.github/workflows/_deploy_web.yaml
    with:
      build-number: ${{ needs.versioning.outputs.build-number }}
      environment: Staging
    secrets:
      # TODO: We might need to move this to GH Actions secrets
      role-to-assume: arn:aws:iam::257498453293:role/jobox-github-action-staging-denali
      aws-region: us-west-2
      ecr-repository: denali/staging/web

  deploy-api:
    name: Deploy DENALI API to AWS
    needs: [versioning]
    uses: ./.github/workflows/_deploy_api.yaml
    with:
      build-number: ${{ needs.versioning.outputs.build-number }}
      environment: Staging
    secrets:
      # TODO: We might need to move this to GH Actions secrets
      role-to-assume: arn:aws:iam::257498453293:role/jobox-github-action-staging-denali
      aws-region: us-west-2
      ecr-repository: denali/staging/api

  pre-release:
    name: Create Github pre-release & release notes
    needs: [versioning, deploy-web, deploy-api]
    uses: ./.github/workflows/_pre_release.yaml
    with:
      build-number: ${{ needs.versioning.outputs.build-number }}
      environment: Staging
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  restart-staging:
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-api]
    environment: Staging
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # TODO: We might need to move this to GH Actions secrets
          role-to-assume: arn:aws:iam::257498453293:role/jobox-github-action-staging-denali
          aws-region: us-west-2

      - name: Restart Staging API
        run: |
          aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"InstanceIds","Values":["i-022feced8398583f3"]}]' --parameters '{"commands":["runuser -l ec2-user -c /opt/webapps/scripts/pull_and_restart_api.sh"],"workingDirectory":[""],"executionTimeout":["3600"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --cloud-watch-output-config '{"CloudWatchLogGroupName":"stg-denali-api-deployment","CloudWatchOutputEnabled":true}' --region us-west-2
