name: DENALI CD (Deploy Production)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  code-checks:
    name: Run code quality tools
    uses: ./.github/workflows/_code_checks.yaml

  versioning:
    name: Generate build number
    uses: ./.github/workflows/_versioning.yaml

  deploy-docs:
    name: Deploy DENALI Docs to Github Pages
    uses: ./.github/workflows/_deploy_docs.yaml

  deploy-web:
    name: Deploy DENALI Web to AWS
    needs: [versioning]
    uses: ./.github/workflows/_deploy_web.yaml
    with:
      build-number: ${{ needs.versioning.outputs.build-number }}
      environment: Production
    secrets:
      # TODO: We might need to move this to GH Actions secrets
      role-to-assume: arn:aws:iam::257498453293:role/jobox-github-action-production-denali
      aws-region: us-west-2
      ecr-repository: denali/web

  deploy-api:
    name: Deploy DENALI API to AWS
    needs: [versioning]
    uses: ./.github/workflows/_deploy_api.yaml
    with:
      build-number: ${{ needs.versioning.outputs.build-number }}
      environment: Production
    secrets:
      # TODO: We might need to move this to GH Actions secrets
      role-to-assume: arn:aws:iam::257498453293:role/jobox-github-action-production-denali
      aws-region: us-west-2
      ecr-repository: denali/api

  release:
    name: Create Github release & release notes
    needs: [deploy-web, deploy-api]
    uses: ./.github/workflows/_release.yaml
    with:
      build-number: ${{ needs.versioning.outputs.build-number }}
      environment: Production
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  restart-production:
    runs-on: ubuntu-latest
    needs: [deploy-web, deploy-api]
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Restart Production API
        run: |
          aws ssm send-command --document-name "AWS-RunShellScript" --document-version "1" --targets '[{"Key":"InstanceIds","Values":["i-0de9370e9b06eab16"]}]' --parameters '{"commands":["runuser -l ec2-user -c /opt/webapps/scripts/pull_and_restart_api.sh"],"workingDirectory":[""],"executionTimeout":["3600"]}' --timeout-seconds 600 --max-concurrency "50" --max-errors "0" --cloud-watch-output-config '{"CloudWatchLogGroupName":"prd-denali-api-deployment","CloudWatchOutputEnabled":true}' --region us-west-2
