name: DENALI CI

on:
    push:
        branches: [master, develop]
    pull_request:
        branches: [master, develop]

jobs:
    container-job:
        name: DENALI CI
        runs-on: ubuntu-latest
        container: node:22.14.0-slim

        steps:
            - name: Check out code
              uses: actions/checkout@v4
