name: DENALI CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  container-job:
    name: DENALI CI
    runs-on: ubuntu-latest
    container: node:22.14.0-slim

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn run lint

      - name: Run tests unit
        run: yarn run test:unit

      - name: Run tests e2e
        run: yarn run test:e2e

      - name: Run API build
        run: yarn turbo run build --filter=@denali/api

      - name: Run WEB build
        run: yarn turbo run build --filter=@denali/web
        env:
          FRONTEGG_ENCRYPTION_PASSWORD: ""